server:
  port: 8085  # API Gateway runs on this port

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/users/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
